language: c
dist: trusty
sudo: false
cache:
  ccache: true
  directories:
    - $HOME/dieharder

stages:
  - compile
  - test
jobs:
  include:
    - stage: compile
      addons:
        apt:
          packages:
            - libgsl0-dev

      before_install:
        - rm -rf manual # no need for it
      install:
        - ./autogen.sh
        - ./configure --prefix=$HOME/dieharder
        - make
        - make install
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test
    - stage: test

before_script:
  - DIEHARDER_TEST=(0 1 2 3 4 8 9 10 11 12 13 15 16 17 100 101 101 102 200 201 202 203 204 205 206 207 208 209)
script:
  - $HOME/dieharder/bin/dieharder -d ${DIEHARDER_TEST[${TRAVIS_JOB_NUMBER##*.}]}
